
version: '3.7'

services:

  creator-client:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_CREATOR_CLIENT_PORT ]
      context: src/client
    container_name: test-creator-client
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - creator
    image: cyberdojo/creator-client
    init: true
    ports: [ "${CYBER_DOJO_CREATOR_CLIENT_PORT}:${CYBER_DOJO_CREATOR_CLIENT_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]
